### ISSUE TITLE
App crash on image attaching in alerts

### ISSUE THREAD

**Issue by regolo85** [smartcommunitylab/smartcampus.vas.rifiuti.android#2]
On android 4.1.2, if I try to attach an image to an alert, the app crash. 
The error log is:
"Out of memory on a 31961104-byte allocation.
FATAL EXCEPTION: main
java.lang.OutOfMemoryError
    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:652)
    at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
    at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:451)
    at android.provider.MediaStore$Images$Media.insertImage(MediaStore.java:810)
    at eu.trentorise.smartcampus.rifiuti.FeedbackFragment.onActivityResult(FeedbackFragment.java:207)
    at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:166)
    at eu.trentorise.smartcampus.rifiuti.MainActivity.onActivityResult(MainActivity.java:367)
    at android.app.Activity.dispatchActivityResult(Activity.java:5390)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3201)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3248)
    at android.app.ActivityThread.access$1200(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at dalvik.system.NativeStart.main(Native Method)"

**Comment by regolo85** [comment]
The problem persists on my Android 4.1.2 device.

**Comment by regolo85** [comment]
With the new app version the problem is solved

**Comment by oskarnrk** [comment]
I added the tag android:largeHeap="true" to prevent this error on some Android versions
